name: DO Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir testx 
            cd testx 
            git clone git@github.com:ViktorDyukov/portfolio-frontend.git 
            echo 'Deployment successful to digital ocean'
