name: DO Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir temp_fe 
            cd temp_fe 
            git clone git@github.com:ViktorDyukov/portfolio-frontend.git 
            rm /home/react/portfolio-frontend-build/*.*
            cp -r portfolio-frontend/build/ /home/react/portfolio-frontend-build/
            cd ..
            rm -r temp_fe
